// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZtcR7wCSrYatzih8FmPQCZt0ec7qb3A',
    appId: '1:402349873856:web:899311e92d6d4d73b6ab25',
    messagingSenderId: '402349873856',
    projectId: 'ipp-databas',
    authDomain: 'ipp-databas.firebaseapp.com',
    databaseURL: 'https://ipp-databas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ipp-databas.firebasestorage.app',
    measurementId: 'G-BXJ048M1K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIWDurP4Aw-6_ax4OtXYRx3SVC-EsEf8',
    appId: '1:402349873856:android:9c3e32dcd2de5681b6ab25',
    messagingSenderId: '402349873856',
    projectId: 'ipp-databas',
    databaseURL: 'https://ipp-databas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ipp-databas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA324wA6xavobuTW0sVTR4sKggni2xGO7s',
    appId: '1:402349873856:ios:97b8f35643df937fb6ab25',
    messagingSenderId: '402349873856',
    projectId: 'ipp-databas',
    databaseURL: 'https://ipp-databas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ipp-databas.firebasestorage.app',
    iosBundleId: 'com.example.appIpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA324wA6xavobuTW0sVTR4sKggni2xGO7s',
    appId: '1:402349873856:ios:97b8f35643df937fb6ab25',
    messagingSenderId: '402349873856',
    projectId: 'ipp-databas',
    databaseURL: 'https://ipp-databas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ipp-databas.firebasestorage.app',
    iosBundleId: 'com.example.appIpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZtcR7wCSrYatzih8FmPQCZt0ec7qb3A',
    appId: '1:402349873856:web:a18e933605af523bb6ab25',
    messagingSenderId: '402349873856',
    projectId: 'ipp-databas',
    authDomain: 'ipp-databas.firebaseapp.com',
    databaseURL: 'https://ipp-databas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ipp-databas.firebasestorage.app',
    measurementId: 'G-6129F1NSJ7',
  );
}
